package commentmodel

import "time"

type Comment struct {
	// comment id generated by mongo
	ID string `bson:"_id,omitempty" json:"id"`
	// required task id what was complited
	TaskID string `bson:"task_id" json:"task_id"`
	// required task type from task info
	TaskType string `bson:"task_type" json:"task_type,omitempty"`
	// required user id who commented
	CreatorID string `bson:"creator_id" json:"creator_id"`
	// required worker id is who user commented
	WorkerID string `bson:"worker_id" json:"worker_id"`
	// required like or not worker work
	IsLike bool `bson:"is_like" json:"is_like"`
	// required description of comment
	Description string `bson:"description" json:"description"`
	// Creation date UTC
	CreatedAt time.Time `bson:"created_at,omitempty" json:"created_at"`
	// updated date UTC
	UpdatedAt time.Time `bson:"updated_at,omitempty" json:"updated_at"`
}

type CountLikeDislikeWorker struct {
	Likes   int `json:"likes"`
	Dislike int `json:"dislikes"`
}

type CommentCreateRes struct {
	CommentID string `json:"comment_id"`
}
